# Generated by Django 5.1 on 2024-09-03 12:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_discount_tax_item_currency_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Налог', 'verbose_name_plural': 'Налоги'},
        ),
        migrations.AddField(
            model_name='discount',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Скидка в %'),
        ),
        migrations.AddField(
            model_name='discount',
            name='duration',
            field=models.CharField(choices=[('frv', 'forever'), ('once', 'once'), ('rpt', 'repeating')], default='once', max_length=4, verbose_name='Продолжительность'),
        ),
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(default='default', max_length=100, verbose_name='Купон'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_disc', to='payment.discount', verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order_tax', to='payment.tax', verbose_name='Налог'),
        ),
        migrations.AddField(
            model_name='tax',
            name='tax',
            field=models.DecimalField(db_index=True, decimal_places=2, default=13.0, max_digits=4, unique=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Налог в %'),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rub', 'rub'), ('usd', 'usd')], default='rub', max_length=3, verbose_name='Валюта'),
        ),
    ]
