# Generated by Django 5.1 on 2024-09-04 11:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_discount_options_alter_tax_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='tax',
            name='country',
            field=models.CharField(blank=True, default='RU', help_text='(ISO 3166-1 alpha-2)', max_length=2, null=True, verbose_name='Код страны'),
        ),
        migrations.AddField(
            model_name='tax',
            name='inclusive',
            field=models.BooleanField(default=False, help_text='Указывает, является ли ставка налога инклюзивной или эксклюзивной', verbose_name='Инклюзивная ставка'),
        ),
        migrations.AddField(
            model_name='tax',
            name='name',
            field=models.CharField(default='НДС', max_length=100, verbose_name='Название налога'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название купона'),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rub', 'руб'), ('usd', 'USD')], default='rub', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_tax', to='payment.tax', verbose_name='Налог'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(help_text='E-mail', max_length=100, unique=True, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Налог в %'),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='payment.item', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='payment.order', verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Товар корзины',
                'verbose_name_plural': 'Товары корзины',
                'unique_together': {('order', 'item')},
            },
        ),
    ]
