# Generated by Django 5.1 on 2024-09-05 04:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_order_items_tax_country_tax_inclusive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_currency',
            field=models.CharField(choices=[('rub', 'руб'), ('usd', 'USD')], default='rub', max_length=3, verbose_name='Валюта корзины'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.50'))], verbose_name='Итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.50'))], verbose_name='Стоимость'),
        ),
    ]
